clientID: "<client-id>"
clientSecret: "<client-secret>"
oidcIssuer: "https://<domain.tld>/oauth2/openid/<resource-server>"
callbackURL: "https://<domain.tld>/callback"
listenAddr: ":8080"
tlsCert: "path/to/your/optional/cert.pem"
tlsKey: "path/to/your/optional/key.pem"
endpoints:
  - path: "/public"
    public: true
    command:
      - "echo"
      - "Hello world!"
  - path: "/private"
    command:
      - "echo"
      - "{{.AuthClaims.PreferredUsername}}"
  - path: "/custom-html"
    command:
      - "echo"
      - "You can use custom HTML files for presenting the output of a command."
    htmlFile: "custom.html"
  - path: "/get-file"
    binaryOutput: true
    command:
      - "cat"
      - "file.png"
    requiredGroups:
      - "admins"
